theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "used"
format = "{icon} {used}/{total} (free: {available})"
unit = "GB"
interval = 60
warning = 60.0
alert = 90.0

[[block]]
block = "disk_space"
path = "/home"
alias = "/home"
info_type = "used"
format = "{icon} {used}/{total} (free: {available})"
unit = "GB"
interval = 60
warning = 60.0
alert = 95.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "net"
device = "wlp5s0"
format = "{ssid} {signal_strength} {ip}"
interval = 60
hide_missing = true

[[block]]
block = "net"
device = "enp4s0"
format = "{ip}"
interval = 60
hide_missing = true

[[block]]
block = "net"
device = "tun0"
format = "{ip}"
interval = 60
hide_missing = true

[[block]]
block = "time"
interval = 5
format = "%Y-%m-%d %H:%M"

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"
